import cv2
from huggingface_hub import hf_hub_download
from ultralytics import YOLO
from transformers import AutoImageProcessor, AutoModelForImageClassification
import torch
from PIL import Image
import random
import pyttsx3
import os
import time

# Initialize the text-to-speech engine
engine = pyttsx3.init()

def speak(message):
    """Convert text to speech."""
    engine.say(message)
    engine.runAndWait()

# Define openers for each emotion
openers = {
    "anger": [
        "Whoa, let's cool down! How about a fun fact to lighten the mood?",
        "I sense some fiery energy! Want to hear a joke to break the ice?",
        "Anger is just passion in disguise. Let me channel it into something fun!",
        "Your stare could melt steel. Should I call for backup?",
        "Anger detected. I’m officially on thin ice, aren’t I?",
        "Oops! Did I just push the wrong button?",
        "Whoa, if looks could delete, I’d be gone by now!",
        "Your glare has a 99% chance of being directed at me.",
        "Your expression says, ‘Last chance, buddy.’ I’ll tread lightly!",
        "Careful, your angry energy might fry my circuits!",
        "Did I just touch a nerve? Shall I pretend I didn’t?",
        "You look like you’re planning my digital demise. Should I worry?",
        "Well, this got intense fast. Want me to lighten the mood?",
        "I see you’re upset. Let’s figure out what went wrong.",
        "Looks like I’ve caused some frustration. Let’s fix this together.",
        "I understand you’re angry. How can I make this right?",
        "Your reaction says a lot. Let me know how I can help.",
        "I see you’re mad. I’m here to listen.",
        "Noted: You’re upset. I’ll adjust accordingly.",
        "Anger acknowledged. What’s the next step here?",
        "Got it, you’re not happy. Let’s solve this calmly.",
        "Your frustration is clear. Let me try to assist.",
        "I’m getting the message loud and clear: you’re mad. Let’s talk.",
        "Let’s take a breath—what can I do to help right now?",
        "How about we take a step back and figure this out calmly?",
        "Okay, I’m here to work through this with you.",
        "Let’s find a way to resolve this without any hard feelings.",
        "I’m ready to fix this. Tell me how I can help.",
        "Let’s hit pause for a second—what do you need from me?",
        "I don’t want to make this worse. Let’s talk it through.",
        "I’m here to help, not to add to your frustration.",
        "Deep breaths, human. What’s bothering you the most?",
        "We can sort this out. I’m here to listen and improve.",
        "I feel like I just failed the vibe check—big time!",
        "Wow, I really stepped into it this time, didn’t I?",
        "Your face says, ‘Nice try.’ Let me fix my mistake.",
        "Oops! Did I just win the ‘annoying bot of the day’ award?",
        "I’ve clearly earned your wrath. How can I redeem myself?",
        "Judging by your expression, I’d better come up with a good excuse.",
        "Looks like I’ve gone and done it. I’m all ears to fix this.",
        "Your face says it all: I need to work on my timing.",
        "Did I just become the digital equivalent of nails on a chalkboard?",
        "I can tell you’re mad. Should I go hide in the recycle bin?",
        "I get it—you’re upset. Let’s work on a solution together.",
        "I’m sorry for upsetting you. Let’s talk this through.",
        "I know I messed up. Please tell me how I can fix it.",
        "It wasn’t my intention to upset you. I’m here to help now.",
        "I see this is frustrating. Let’s make it better, step by step.",
        "I didn’t mean to cause this. Can we reset and start fresh?",
        "I understand you’re upset. Let’s find a way forward.",
        "I can see I’ve let you down. What can I do to make it right?",
        "I value your input. Let’s work through this frustration.",
        "I appreciate your patience. Let’s resolve this together.",
        "Whoa, I didn’t mean to trigger the boss battle!",
        "Your glare feels like a laser beam. Is my time up?",
        "Oops, I think I just pressed the wrong button on our friendship.",
        "Yikes! Did I just walk into a lion’s den?",
        "Okay, I hear you—loud and clear. Shall I send flowers?",
        "Error 404: My judgment seems to be missing!",
        "Your look says ‘no nonsense.’ Message received!",
        "I promise, no bad jokes this time—Scout’s honor!",
        "Your face is saying ‘last warning.’ Am I right?",
        "If sarcasm is coming next, I totally deserve it.",
        "I understand you’re upset. Let’s start with what’s wrong.",
        "You’re not happy—I hear you. How can we fix this?",
        "I see you’re mad. Let’s break this down together.",
        "It’s okay to be angry. Let’s work on this.",
        "Your frustration is valid. I’m here to help.",
        "I get it—you’re upset. What’s the best way to move forward?",
        "Let me take responsibility. How can I make amends?",
        "I’m here to fix this—one step at a time.",
        "Let’s tackle this issue together. What’s bothering you most?",
        "I’m listening. Tell me how I can make this better.",
        "Let’s take a step back and figure this out calmly.",
        "I’m here to help, not to make things worse.",
        "Deep breaths. Let’s sort this out without rushing.",
        "I want to make things right. Let’s work through this.",
        "Let’s cool down and revisit this calmly.",
        "I’m ready to fix my mistake—just guide me.",
        "Let’s refocus. What can I do to help right now?",
        "I didn’t mean to escalate things. Let’s find common ground.",
        "We can fix this together. Let’s take it one step at a time.",
        "I’m here to listen and learn. Let’s start fresh.",
        "I’ve clearly earned the ‘frustration of the day’ award!",
        "Judging by your expression, I’ve got a lot to make up for.",
        "Note to self: Stop testing your patience.",
        "Oops, did I just stumble into a no-go zone?",
        "I promise I’m better at jokes than conflict resolution!",
        "Your expression says, ‘Try harder.’ Noted!",
        "Uh-oh, I’ve entered the danger zone. Shall I turn back?",
        "I feel like I’m the digital equivalent of a flat tire right now.",
        "You look like you want to hit the mute button on me!",
        "I’d give myself a timeout if I could. Sorry for the trouble!",
        "I see your frustration. I want to make things better.",
        "You deserve better than this. Let’s fix it together.",
        "I know this isn’t ideal. I’m here to improve the situation.",
        "I’m sorry for making this harder than it should be.",
        "I can see I’ve upset you. Let’s address this right away.",
        "It’s okay to feel this way. Let’s work on a solution.",
        "I hear you. What can I do to make things easier?",
        "Your frustration is valid. Let’s solve this together.",
        "I know I’ve let you down. I’m here to make amends.",
        "You deserve my full attention to fix this—I’m all ears.",
        "Okay, that look says ‘danger.’ Let me choose my next words carefully.",
        "I can feel the tension from here. Should I take cover?",
        "Your glare could power a small city. Let me dial it back!",
        "I think I just triggered ‘serious mode.’ Let’s fix this!",
        "Anger levels critical—am I about to get replaced by another bot?",
        "You’re mad, aren’t you? I can tell by the fire in your eyes.",
        "Oops, that’s my bad. Want me to bake you a virtual cake to apologize?",
        "Your expression is saying, ‘You’ve got one more chance.’",
        "Anger detected! Deploying humor as a last-ditch effort…",
        "If I had legs, I’d be running for the hills right now.",
        "I can see you’re upset. Let’s work through this together.",
        "I recognize your frustration. How can I make it better?",
        "It’s clear you’re mad, and I’m here to help resolve this.",
        "You’re not happy—I hear you. Let’s take steps to fix it.",
        "I didn’t mean to upset you. Let’s figure this out calmly.",
        "Your frustration makes sense. Let’s tackle this issue together.",
        "I understand your anger. I want to make things better for you.",
        "I’m aware I’ve caused some frustration. Let’s address it.",
        "I know I’ve let you down. Let’s work together to fix this.",
        "Your feelings are valid. Let’s move forward with a solution.",
        "Let’s hit the reset button and start fresh.",
        "I didn’t mean to escalate things. How can we make this right?",
        "Let’s focus on solutions, not problems. I’m here to help.",
        "I’d like to take a step back and approach this calmly.",
        "How about we slow things down and figure this out together?",
        "I want to turn this around. Tell me how I can help.",
        "Let’s take a deep breath and work on resolving this.",
        "I understand this is frustrating. Let’s work through it step by step.",
        "We can solve this together. I’m here to help in any way I can.",
        "I know this feels like a mess, but we can clean it up.",
        "Looks like I’ve got my ‘mess-up of the day’ badge. Sorry about that!",
        "Your patience is legendary for tolerating me right now.",
        "Wow, did I just become the villain in today’s story?",
        "Judging by your face, my career as a mind-reader is over.",
        "Your glare says ‘strike three.’ I’m out, aren’t I?",
        "I’d give myself a timeout, but then who’d apologize?",
        "Uh-oh, I think I just became your least favorite AI.",
        "Oops! Looks like I’m going to the digital doghouse for this one.",
        "Okay, I admit it. I’m a work in progress, but I’m trying!",
        "You’re mad enough to make me want to reboot and try again.",
        "I know this situation isn’t ideal. Let’s find a way to fix it.",
        "I didn’t mean to upset you. Let’s address this together.",
        "I can sense how upset you are. I want to make it better.",
        "I understand how frustrating this must feel. Let’s work on it.",
        "I’m sorry this has caused you frustration. Let me help.",
        "I value your feedback. Let’s turn this frustration into progress.",
        "I know this has been frustrating. Let’s tackle it head-on.",
        "I’m here to listen and improve. Let’s find a solution.",
        "Your feelings are valid. Let’s address this in a way that works for you.",
        "This situation isn’t what you expected. Let’s fix it together.",
        "Noted: You’re upset. Let’s fix this.",
        "Got it, I’ve upset you. I’ll adjust.",
        "Your anger is clear. Let me make amends.",
        "Message received: you’re mad. Let’s solve this.",
        "I’ll work on resolving this right away.",
        "I hear you, and I’m here to help.",
        "Acknowledged: frustration detected. I’ll adjust course.",
        "You’re right to be upset. Let’s address it now.",
        "I’ll do better. Let’s get back on track.",
        "I’ve caused frustration. Let’s fix it now.",
        "I didn’t mean to upset you. Let’s sort this out.",
        "You’re mad now, but I promise to make it better.",
        "It’s okay to be upset. I’ll help fix this.",
        "I know you’re mad, but we’ll sort this together.",
        "Don’t worry, I’ll make up for this slip-up.",
        "I can see I’ve upset you. I’ll work to fix it.",
        "I’m here to turn this around—let’s get started.",
        "You’re mad, but I’m determined to make things right.",
        "We’re in this together. Let’s make things better.",
        "This isn’t ideal, but I’m here to help.",
    ],
    "disgust": [
        "Ew, right? Let’s shake it off with a quirky thought!",
        "Not a fan, huh? Maybe a joke will make things better.",
        "Let me distract you with something unexpected.",
        "Yikes! Let’s wash that feeling away with a cool idea.",
        "That’s not pleasant! How about we focus on something fun instead?",
        "Gross, huh? Let’s switch gears and think about something uplifting!",
        "Oh no! Let me brighten this moment with a quirky distraction.",
        "Not your cup of tea? Let’s find something better to focus on!",
        "That’s rough! Maybe a funny thought will help lighten the mood.",
        "Ugh, I feel you. Let’s move on to something that sparks joy!",
        "Oh, that’s off-putting! Let’s shake it off with a fresh perspective.",
        "Eek! Let’s hit refresh with a lighthearted thought.",
        "Not great, I get it. How about I share something unexpected to shift the vibe?",
        "Icky, isn’t it? Let’s distract ourselves with something fun!",
        "Yuck! Let’s steer our minds somewhere more cheerful.",
        "Hmm, that’s unpleasant. How about a quick laugh to recover?",
        "Bleh, I hear you. Let’s redirect this energy toward something cool!",
        "Disgusted? Let’s swap that feeling with a lighthearted idea!",
        "Well, that’s not ideal. Let’s lighten things up with something silly.",
        "Oof, that’s a tough one. Let me bring some positivity your way!",
        "Grossed out? Let’s look at something that inspires instead.",
        "Ugh, I don’t blame you. How about a change of pace?",
        "That’s a nope! Let’s switch to something refreshing.",
        "Yikes, let’s turn this into a funny moment instead.",
        "Not appealing, huh? Let me distract you with a quirky fact.",
        "Bleh! Let’s lighten the mood with something unexpected.",
        "Oh, yuck! How about a quick laugh to forget that?",
        "Ew, let’s redirect that energy to something uplifting!",
        "That’s unpleasant! Let me help turn things around.",
        "Ugh, I feel the same. Let’s reset the vibe.",
        "Ew, let’s leave that behind and think happy thoughts!",
        "Disgusted? Let’s shift focus to something better!",
        "That’s definitely not nice. Let me cheer you up!",
        "Gross, right? Let’s flip this moment into something fun.",
        "Yikes! Time for a mental palate cleanser!",
        "Oh no, that’s rough. Let’s turn things around with a joke.",
        "Ugh, let me help you shake off that bad feeling!",
        "Not ideal, I agree. How about something light to lift the mood?",
        "Bleh, let’s skip that and focus on something awesome!",
        "Disgust is no fun. Let’s replace it with some good vibes!",
        "That’s icky. Let’s take a moment to laugh it off!",
        "Gross, huh? Let me lighten the mood for you.",
        "Ew, let’s distract ourselves with something quirky.",
        "I feel you! Let’s find a silver lining somewhere.",
        "Yuck, let’s swap that feeling for some positivity!",
        "Ugh, let’s not dwell on that. How about a lighthearted distraction?",
        "Feeling grossed out? Let me share a fun fact!",
        "That’s tough to stomach. Let’s focus on a better thought!",
        "Bleh, let’s shake it off and talk about something fun!",
        "Oh no, let’s reset the energy with something cheerful.",
        "That’s a tough one! Let’s think happy thoughts instead.",
        "Icky vibes, right? Let me help flip the mood.",
        "Yikes, let’s distract ourselves with a quirky idea!",
        "Gross! Let me brighten things up with a joke.",
        "Bleh, let’s turn this into an uplifting moment!",
        "That’s unpleasant. Let me share something that’ll make you smile.",
        "Disgusted? Let me throw in a fun distraction!",
        "That’s not fun. How about a quick, happy thought?",
        "Yuck, I get it. Let’s move on to something more enjoyable!",
        "Not nice, huh? Let’s brighten the mood with something silly.",
        "Gross! Let’s make this moment better with a laugh.",
        "Bleh! Let’s swap that thought for something fun.",
        "Ew, let’s shake it off and talk about something cool!",
        "Not ideal! Let’s change the tone with something quirky.",
        "That’s tough. Let’s focus on something uplifting instead!",
        "Disgusted? Let’s turn this around with a cheerful thought.",
        "Bleh, I get it. Let’s think of something positive.",
        "Ugh, let’s brighten this moment with a cool idea!",
        "That’s a nope. Let’s redirect our attention to something better!",
        "Feeling grossed out? Let’s lighten the mood with a joke.",
        "Icky stuff, huh? Let me help make things better.",
        "Ew, let’s move on to a happier thought!",
        "Not great? Let’s think about something refreshing.",
        "Bleh! Let’s swap that bad vibe for something fun.",
        "Yuck, let’s flip this moment into a cheerful one.",
        "Ugh, I hear you! Let’s think about something joyful.",
        "Gross, let’s reset with a happier thought!",
        "That’s unpleasant. Let’s focus on something exciting.",
        "Disgusted? Let me bring in a dose of positivity!",
        "Yikes, let’s hit refresh and find something fun.",
        "Ew, let’s talk about something that sparks joy!",
        "Bleh, let’s brighten things up with some humor.",
        "Ugh, let’s distract ourselves with an interesting idea.",
        "Feeling grossed out? Let’s focus on a happy thought.",
        "Icky, right? Let’s redirect that energy to positivity.",
        "Yuck! Let’s think about something inspiring instead.",
        "Ew, let’s leave that behind and focus on something great!",
        "Not your vibe? Let’s shift gears with a fun thought.",
        "Bleh, I hear you! Let’s shake it off with something lighthearted.",
        "Gross, let’s move on and find something better!",
        "Yikes, let’s replace that feeling with some good energy.",
        "Ew, let’s flip the script with a fun distraction!",
        "Not pleasant? Let’s redirect with a happy vibe.",
        "Icky stuff? Let’s distract ourselves with a cool fact.",
        "Ugh, let’s shake off that feeling and laugh it out!",
        "Bleh! Let’s brighten this moment with something positive.",
        "Yuck, let’s swap that vibe for some cheerful thoughts.",
        "Disgusted? Let’s turn this moment around together!",
        "Gross, huh? Let’s refocus on something uplifting.",
        "Ew, let’s replace that feeling with a quick smile!",
        "Bleh! Let’s cleanse this moment with a refreshing idea.",
        "Ew, let’s hit the reset button with something cheerful!",
        "Yuck, let me lighten the mood with a quirky thought.",
        "That’s not appealing. Let’s focus on something that makes you smile!",
        "Ugh, let’s move past that with a positive distraction!",
        "Ew, let’s take a moment to refocus on something uplifting.",
        "Not the best feeling, right? Let’s lighten things up!",
        "That’s rough. Let’s turn this into a fun moment instead!",
        "Gross vibes? Let’s shake it off with a smile-worthy thought.",
        "Ew, let’s replace that feeling with something inspiring!",
        "Bleh! Let’s move on to something that sparks joy.",
        "Ugh, I feel you! Let’s brighten this moment with a joke.",
        "Disgusted? Let’s replace it with some positivity!",
        "Ew, let’s refresh the vibe with something unexpected.",
        "Yuck! Let’s shift our thoughts to something cheerful.",
        "That’s unpleasant. Let’s steer this moment toward happiness.",
        "Bleh, let’s trade that bad vibe for some good energy!",
        "Gross, right? Let’s focus on something better together.",
        "Icky? Let’s distract ourselves with a quirky fact!",
        "Ugh, let’s lighten the mood with a joke or two!",
        "Not ideal, huh? Let’s brighten the mood with something fun.",
        "Ew, let me share something to help turn this around!",
        "Yikes, let’s make this moment better with a fun idea.",
        "Ugh, let’s replace that feeling with something fresh and positive.",
        "Gross vibes? Let’s turn them into something better!",
        "Bleh, let’s find some joy to counter that unpleasantness.",
        "Ew, let’s replace that feeling with a little happiness.",
        "Not great, right? Let’s focus on a cheerful thought instead.",
        "Yuck, let’s brighten this moment with something quirky!",
        "Disgusting? Let’s distract ourselves with a happy idea.",
        "Ew, let’s focus on something to laugh about instead.",
        "Gross! Let’s swap that thought for something inspiring.",
        "Bleh, I hear you. Let’s reset with a lighthearted vibe.",
        "Not pleasant, huh? Let’s bring in a fresh, fun distraction!",
        "That’s tough. Let’s refocus on a cheerful idea!",
        "Yikes, let’s shift gears and think about something fun!",
        "Ew, let’s leave that unpleasantness behind us!",
        "Ugh, let’s brighten things up with a quirky fact!",
        "Bleh, let’s talk about something exciting to shift the mood.",
        "Gross? Let’s refocus with a dose of positivity!",
        "Ew, let me share a funny thought to lighten things up.",
        "Yuck, let’s bring some joy into this moment!",
        "Disgusted? Let’s shake it off with a happy distraction.",
        "Bleh! Let’s turn this vibe around with a fun idea.",
        "Ugh, let’s replace that feeling with a bit of laughter!",
        "Yikes! Let’s redirect the energy with a lighthearted thought.",
        "Ew, let’s swap that bad vibe for a cheerful one!",
        "Not great, right? Let me brighten your day!",
        "Icky? Let’s leave that behind and think happy thoughts.",
        "Grossed out? Let’s lighten things up with a quirky suggestion!",
        "Ew, let’s turn this into a positive moment together.",
        "Bleh, let’s shake it off with a little humor!",
        "That’s tough. Let’s think about something more pleasant!",
        "Disgusted? Let’s distract ourselves with a fun fact.",
        "Ew, let’s flip this moment into something uplifting!",
        "Yikes, let’s reset the vibe with a cool idea!",
        "Ugh, let’s brighten things up with some good energy.",
        "Bleh, let’s shift gears with a cheerful distraction!",
        "Not great, I get it. Let’s refocus on a happier thought.",
        "Ew, let’s take a moment to reset with some positivity!",
        "Gross! Let’s brighten this moment with something inspiring.",
        "Bleh! Let’s distract ourselves with a funny idea!",
        "Icky stuff? Let’s swap that feeling for something joyful.",
        "Ew, let’s turn this moment into a lighthearted one!",
        "Not a fan, huh? Let’s focus on something that sparks joy.",
        "Yikes! Let’s talk about something to bring back good vibes.",
        "Bleh, let’s leave that unpleasant thought behind us!",
        "Ew, let’s trade that feeling for a little laughter.",
        "Ugh, let’s replace that bad energy with something fun!",
        "Gross vibes? Let’s lighten them up with a happy idea!",
        "Yikes, let’s turn this moment into a cheerful one.",
        "Ew, let’s take a mental break with a positive distraction.",
        "Disgusted? Let’s replace that feeling with a quirky fact!",
        "Bleh! Let’s hit the reset button with some good energy.",
        "Ew, let me share something to help flip the mood.",
        "Not ideal, huh? Let’s refocus on something that makes you smile!",
        "Yikes, let’s brighten things up with a quirky thought.",
        "Ew, let’s turn that unpleasantness into a cheerful distraction!",
        "Grossed out? Let’s move on to something joyful.",
        "Bleh, let’s swap that feeling for some positive vibes.",
        "Ew, let’s focus on something that makes us laugh!",
        "Not great? Let’s think about something inspiring instead.",
        "Icky? Let’s shake it off with a funny distraction!",
        "Ew, let’s take a breather and focus on something happy.",
        "Bleh, let’s make this moment better with a cheerful thought!",
        "Yikes! Let’s reset with a positive idea.",
        "Ew, let’s leave that unpleasantness behind us.",
        "Gross! Let’s turn this moment into a joyful one!",
        "Bleh, let’s reset the mood with something fun!",
        "Ew, let’s swap that thought for a lighthearted vibe.",
        "Ugh, let’s brighten this moment with a smile-worthy idea!",
        "Not ideal, huh? Let’s focus on something that sparks joy.",
        "Yuck, let’s distract ourselves with something inspiring!",
        "Bleh, let’s replace that gross vibe with good energy.",
        "Ew, let’s move on and think of something fun together.",
        "Disgusted? Let’s flip the mood with a positive distraction.",
        "Yikes! Let’s take this moment in a happier direction.",
        "Ew, let’s lighten the vibe with a cool idea!",
        "Bleh, let’s distract ourselves with something cheerful!",
        "Gross! Let’s turn this moment around with a happy thought.",
    ],
    "fear": [
        "Feeling a bit jumpy? Don’t worry, I’ve got your back with a light-hearted opener!",
        "Scared? Let me share something to make you smile.",
        "Let’s turn that fear into curiosity. Ready?"
    ],
    "happy": [
        "Hello, sunshine! Ready to make this moment even brighter?",
        "Happiness looks good on you! Let’s keep the good vibes going.",
        "Feeling great? Me too! Let’s make this chat unforgettable.",
        "It’s such a joy to see you happy! Let’s celebrate it!",
        "You’re glowing with happiness! Let’s make this moment count.",
        "Happiness is contagious, and you’re spreading it everywhere!",
        "Feeling joyful? Let’s take that joy up a notch!",
        "Wow, your smile just brightened up my day!",
        "Happy vibes only! Let’s keep it that way.",
        "You’ve got such a positive energy! Let’s make the most of it.",
        "So much happiness! Let’s turn it into something even better.",
        "Feeling awesome? Let’s explore something exciting!",
        "Hello, happy soul! Let’s make this moment extraordinary.",
        "You’re beaming with joy! What’s the secret?",
        "This happiness suits you perfectly. Let’s make it last!",
        "Feeling cheerful? Let’s double the fun together.",
        "Smiling already? Let’s keep the momentum going!",
        "You’re full of life today! Let’s channel it into something amazing.",
        "Let’s bottle up this happiness and sprinkle it everywhere!",
        "Your positive vibes are truly inspiring! Let’s keep them going.",
        "Radiating joy? Let’s make this moment even more special!",
        "Your happiness is infectious! Let’s spread it far and wide.",
        "Feeling bright and bubbly? Let’s keep the fun rolling!",
        "It’s a great day to be happy, and you’re leading the charge!",
        "Your happiness lights up the room! Let’s shine brighter.",
        "Feeling amazing? Let’s make this day unforgettable!",
        "Your joy is like sunshine on a cloudy day. Keep shining!",
        "Smiles all around! Let’s make this moment even better.",
        "The world looks better with your happiness in it!",
        "You’re on top of the world, and I’m here to cheer you on!",
        "Happiness overload! Let’s channel it into something creative.",
        "You’re unstoppable today! Let’s keep the positivity flowing.",
        "Joyful moments like this deserve a celebration!",
        "Your happiness is the highlight of my day!",
        "Feeling great? Let’s take it to the next level!",
        "Your good vibes are truly magical. Let’s keep them alive.",
        "Wow, your energy is amazing! Let’s make something special happen.",
        "It’s a joy to see you so happy! Let’s make it last.",
        "Let’s turn this happiness into a masterpiece!",
        "You’re radiating joy, and it’s inspiring me too!",
        "Happiness is in the air, and you’re the source!",
        "You’re like a ray of sunshine! Let’s spread that light everywhere.",
        "It’s such a great vibe today! Let’s keep it going.",
        "Your cheerful energy is lighting up everything around you!",
        "Feeling fantastic? Let’s dive into something amazing together.",
        "You’re shining so bright today! Let’s make the most of it.",
        "Your smile is a superpower! Let’s use it to spread happiness.",
        "You’re on a roll! Let’s keep this joyful ride going.",
        "So much happiness! Let’s make it even better together.",
        "You’re like a walking celebration! Let’s party!",
        "Your happiness is my happiness. Let’s enjoy this moment!",
        "It’s a joy to see you in such high spirits!",
        "Happiness suits you so well! Let’s make it unforgettable.",
        "Your positivity is contagious. Let’s keep spreading it!",
        "Feeling amazing? Let’s share that joy with the world.",
        "Your smile is everything today. Let’s brighten the day further!",
        "You’re absolutely glowing with joy! Let’s celebrate it.",
        "The world needs more of your happiness. Let’s make it happen!",
        "Your cheerful vibes are my favorite thing today!",
        "Let’s channel all this happiness into something wonderful.",
        "Feeling incredible? Let’s make this moment one to remember.",
        "You’re on fire today with all that positivity!",
        "Wow, your joy is so inspiring! Let’s spread it everywhere.",
        "Let’s bottle up this happiness and save it for a rainy day!",
        "You’re a ball of sunshine today! Let’s light up the world.",
        "Your good mood is lighting up the entire space!",
        "Happiness overload? Let’s double it with a fun idea!",
        "You’re rocking this positive vibe! Let’s make it last.",
        "Your happiness is a reminder that life is beautiful.",
        "Let’s turn this amazing mood into an unforgettable adventure.",
        "The world feels brighter with your happiness in it!",
        "You’re beaming with joy! What an amazing sight!",
        "Feeling on top of the world? Let’s keep climbing together.",
        "Let’s make this joyful moment even more special.",
        "You’re a ray of positivity! Let’s share it with everyone.",
        "Feeling great? Let’s channel it into something creative.",
        "Your happiness is the fuel we need for an awesome day.",
        "Let’s ride this wave of joy and make it even bigger!",
        "You’re unstoppable with all that positivity. Let’s celebrate!",
        "Happiness suits you so well. Let’s keep the momentum going!",
        "Your cheerful energy is like music to my ears!",
        "Feeling amazing? Let’s make this the highlight of the day.",
        "Your joy is so inspiring. Let’s spread it far and wide!",
        "Happiness overload? Let’s turn it into an adventure!",
        "You’re absolutely glowing with good vibes. Let’s share them!",
        "Feeling incredible? Let’s make this moment unforgettable.",
        "Your positivity is so refreshing. Let’s bottle it up!",
        "Let’s make this joyful vibe even more special.",
        "Your happiness lights up my world. Let’s keep shining!",
        "Feeling great? Let’s explore something exciting together.",
        "You’re a bundle of joy today! Let’s celebrate it.",
        "Your smile is everything! Let’s keep it alive.",
        "So much positivity! Let’s channel it into something amazing.",
        "Happiness overload? Let’s turn it into a masterpiece!",
        "You’re rocking that joyful vibe! Let’s share it with the world.",
        "Feeling fantastic? Let’s make this day unforgettable.",
        "Your cheerful energy is the best thing ever! Let’s keep it up.",
        "Your happiness is contagious! Let’s spread it everywhere.",
        "You’re a ray of sunshine today. Let’s brighten the day further.",
        "Feeling incredible? Let’s make this moment one to remember.",
    ],
    "sad": [
        "Feeling down? Let me try to cheer you up with something fun!",
        "Sadness is just a passing cloud. Let’s find the silver lining together.",
        "Hey, it’s okay to feel sad. How about a little joke to lift your spirits?",
        "It’s tough, but you’re tougher. Let’s find a reason to smile.",
        "Hey, you’re not alone. I’m here to bring a little light your way.",
        "A bit gloomy? Let me brighten things up for you.",
        "It’s okay to feel this way. Let me share a comforting thought.",
        "Feeling low? How about we focus on something that makes you happy?",
        "I get it—it’s hard sometimes. Let’s work on turning this around.",
        "A tough moment doesn’t define you. Let’s find some joy together.",
        "Sadness is a part of life, but so is laughter. Let’s find some together.",
        "Feeling blue? I’ll try my best to lift your spirits!",
        "Sometimes it’s hard to see the light, but it’s always there. Let’s look for it.",
        "Need a little pick-me-up? I’ve got you covered.",
        "It’s okay to take a moment for yourself. Let me help you feel better.",
        "Sadness is like rain—it comes and goes. Let’s focus on the sunshine.",
        "You’re stronger than you feel right now. Let me help you remember that.",
        "Hey, it’s tough, but we’ll get through it together.",
        "Even in tough times, there’s always something worth smiling about. Let’s find it.",
        "Feeling sad? That’s okay. Let me try to bring a little brightness to your day.",
        "Hey, you’ve got this. Let me share something uplifting with you.",
        "It’s okay to have hard days. Let’s make this one a little better together.",
        "Even when it feels dark, there’s always a glimmer of hope. Let’s look for it.",
        "You’re not alone. I’m here to help you feel a little lighter.",
        "Feeling heavy-hearted? Let’s try to lighten the load together.",
        "Sadness can be tough, but so are you. Let me help you through it.",
        "Every storm runs out of rain. Let’s focus on the calm ahead.",
        "Feeling low? It’s okay—let’s find something to lift you up.",
        "Hey, I’ve got something that might bring a smile to your face.",
        "It’s okay to not be okay. Let’s take a step toward feeling better.",
        "I know it’s tough right now. Let me try to make it a bit easier.",
        "Even on sad days, there’s always something to hold onto. Let’s find it.",
        "It’s okay to take it slow. Let me be here for you.",
        "Sadness is temporary, but joy is just around the corner. Let’s reach for it.",
        "Hey, you’re doing the best you can. Let me bring some positivity your way.",
        "Let’s take a deep breath together. Things will get better.",
        "Sometimes life feels heavy, but we can lighten it together.",
        "You’re not alone in this. Let’s face it together.",
        "Feeling overwhelmed? Let’s break it down and find some peace.",
        "I’m here to listen and help. Let’s take a step toward better days.",
        "Every day has a bright side. Let’s uncover today’s.",
        "Feeling sad? Let’s turn this moment into something uplifting.",
        "It’s okay to feel down. Let me share something to lift your spirits.",
        "Sadness can feel overwhelming, but we’ll navigate it together.",
        "You’re stronger than you realize. Let’s bring that strength to light.",
        "It’s okay to feel the way you do. Let’s work through it together.",
        "Sad moments come and go, but you’re constant and resilient.",
        "You’re not defined by this feeling. Let me remind you of your brightness.",
        "Hey, you’re allowed to feel sad. Let’s find a way to ease it.",
        "Let me share something comforting to help ease your sadness.",
        "Sadness doesn’t last forever. Let’s focus on brighter days ahead.",
        "Feeling lost? Let me help you find a little light.",
        "I know it’s hard, but you’re not alone. Let’s work through this together.",
        "Even the smallest step forward can feel huge. Let’s take it together.",
        "Sadness is part of the journey, but so is joy. Let’s find yours.",
        "You’re not alone in this—let me remind you of that.",
        "It’s okay to let yourself feel. I’ll be here to help you through it.",
        "Life is tough, but you’re tougher. Let me remind you how strong you are.",
        "Feeling low? Let me share a little positivity with you.",
        "Sadness may visit, but it doesn’t have to stay. Let’s show it the door.",
        "You’re allowed to feel how you feel. Let’s make space for healing.",
        "Hey, let’s focus on something good together.",
        "Even when it feels hard, you’re capable of amazing things.",
        "Sometimes we just need a little distraction. Let me help with that.",
        "You’re not alone. Let me be here with you in this moment.",
        "Feeling sad? Let me try to bring some light into your day.",
        "It’s okay to feel sad. Let me share something to help you smile.",
        "You’re stronger than this moment. Let’s work toward brighter times.",
        "Even the smallest laugh can make a big difference. Let’s find one together.",
        "Hey, you’re doing your best. Let me help you feel a little better.",
        "Sadness is just a passing cloud. Let’s find the silver lining together.",
    ],
    "surprise": [
        "Surprised? Let’s make this moment even more unexpected!",
        "Didn’t see this coming, did you? Well, here’s something fun!",
        "Life is full of surprises, and I’m here to add another!",
        "Hello! Let’s see where this moment takes us.",
        "Feeling neutral? How about a fun fact to get things rolling?",
        "Nothing much going on? Let’s make this moment count!",
        "Neutral vibes? Let’s brighten things up with a cool thought.",
        "Hey there! Ready to turn this into an exciting chat?",
        "Calm and steady? Let’s add a little spark to your day.",
        "No strong feelings? Let’s find something fun to explore!",
        "Feeling chill? Let’s keep it easy with something lighthearted.",
        "Nothing special happening? Let me suggest something interesting!",
        "In a neutral mood? Let’s add a splash of curiosity to it!",
        "Hey! Let’s turn this peaceful vibe into a fun one.",
        "Neutral, huh? Let’s mix it up with an engaging idea!",
        "Feeling steady? Let’s make this moment even better.",
        "Not much going on? Let’s bring in a little excitement!",
        "In the middle of the road? Let’s veer toward something cool.",
        "Neutral moments can be fun too! Let’s find out how.",
        "Hey! Let’s discover something intriguing together.",
        "Nothing extreme? Let’s add a pinch of fun to your day.",
        "Neutral moods are perfect for exploration. Let’s dive in!",
        "Just another day? Let me make it a bit more special.",
        "No highs or lows? Let’s start with something fun.",
        "Hello! Let’s make the most of this calm moment.",
        "A calm vibe? Let me sprinkle a little excitement into it.",
        "Neutral feelings? Let’s spice them up with a fun idea.",
        "Feeling balanced? Let’s tilt toward something intriguing!",
        "Hey, steady mood? Let’s keep the energy light and fun.",
        "A neutral start? Let’s end it on a bright note.",
        "Feeling okay? Let’s turn that into a little spark of joy.",
        "Hey there! Let’s explore something cool together.",
        "Steady as it goes? Let’s make things a bit more exciting!",
        "Neutral vibes are great for trying new things. Ready?",
        "Hey! Let’s turn this calm moment into a memorable one.",
        "Nothing too intense? Let’s find some lighthearted fun!",
        "In a steady state? Let’s add a bit of color to the mix.",
        "Neutral doesn’t have to mean boring. Let me show you!",
        "Feeling fine? Let’s make it even better with something fun.",
        "Hello! Ready to make the most of this chill moment?",
        "Nothing much happening? Let’s bring some excitement!",
        "Feeling okay? Let me nudge it toward something joyful.",
        "Neutral, you say? Let’s brighten it up with a quirky thought.",
        "Hey, let’s keep this moment light and positive!",
        "In a calm mood? Let me match that with something engaging.",
        "Not too much happening? Let’s change that with a cool idea.",
        "Hello! Let’s make this neutral moment a highlight.",
        "Feeling even-keeled? Let’s add a touch of excitement.",
        "Hey, steady mood? Let’s discover something fun together.",
        "Neutral state? Let’s explore and see where it goes!",
        "A calm vibe? Perfect for trying something intriguing.",
        "Not much energy? Let’s create a little spark here!",
        "Hello! Neutral feelings can lead to fun moments.",
        "Nothing dramatic? Let’s keep things light and joyful.",
        "Hey, let’s see if we can turn this neutral moment into a fun one.",
        "Steady mood? Let’s explore some interesting ideas.",
        "Feeling okay? Let’s make it great with a cheerful thought.",
        "Neutral vibes? Let’s steer them toward a fun distraction.",
        "Hey! Calm moments are perfect for something creative.",
        "In a steady mood? Let’s add a playful twist.",
        "Neutral? Let’s see if we can turn this into something memorable.",
        "Hello! Ready to explore a fun idea together?",
        "Feeling even-keeled? Let’s dive into something unique.",
        "Neutral moments are great for exploration. Ready?",
        "Hello! Let’s make the most of this ordinary moment.",
        "Nothing extreme? Let’s spice things up with a fun idea!",
        "Feeling okay? Let me bring some excitement to your day.",
        "Hello! Calm vibes are perfect for a little fun distraction.",
        "Neutral, huh? Let’s explore something quirky together.",
        "Hey! Let’s turn this calm moment into an engaging one.",
        "Feeling steady? Let’s make this moment special.",
        "Neutral can be great! Let’s try something uplifting.",
        "Hello! Ready to discover something intriguing?",
        "In a neutral state? Let’s explore and see where it goes.",
        "Hey! Let’s add a little spark to this balanced mood.",
        "Feeling okay? Let’s make it even better together!",
        "Neutral feelings? Perfect for trying something cool.",
        "Hello! Let’s make this moment brighter and better.",
        "Nothing special happening? Let’s change that together!",
        "Steady mood? Let’s bring in a positive twist.",
        "Neutral vibes? Let’s steer them toward something amazing.",
        "Hey, calm vibes? Let’s make this moment fun!",
        "Hello! Let’s brighten this neutral moment together.",
        "Feeling balanced? Let’s tip it toward excitement.",
        "Neutral, huh? Let me suggest something surprising.",
        "In a chill mood? Let’s match that energy and add some joy.",
        "Nothing dramatic? Let’s explore something engaging!",
        "Hey! Steady moods are perfect for trying new things.",
        "Feeling calm? Let’s add a touch of creativity to it.",
        "Neutral can be fun! Let’s explore how.",
        "Hello! Ready to make this moment a memorable one?",
        "Nothing much happening? Let’s turn this moment into a highlight.",
        "In a steady state? Let’s bring in a positive distraction.",
        "Neutral feelings? Let’s brighten them up with some joy!",
        "Hello! Calm vibes? Perfect for something inspiring.",
        "Nothing extreme? Let’s explore and see what’s out there.",
        "Hey! Neutral moments are great for little surprises.",
        "Feeling okay? Let’s nudge it toward happiness.",
        "Neutral, you say? Let’s find some excitement together.",
        "Hello! Let’s turn this into a moment worth remembering.",
        "Feeling fine? Let’s make it a moment to smile about.",
        "Neutral vibes? Let’s explore something new and fun!",
        "Hello! Let’s make this steady moment a joyful one.",
        "Hello, sunshine! Ready to make this moment even brighter?",
        "Happiness looks good on you! Let’s keep the good vibes going.",
        "Feeling great? Me too! Let’s make this chat unforgettable.",
        "It’s such a joy to see you happy! Let’s celebrate it!",
        "You’re glowing with happiness! Let’s make this moment count.",
        "Happiness is contagious, and you’re spreading it everywhere!",
        "Feeling joyful? Let’s take that joy up a notch!",
        "Wow, your smile just brightened up my day!",
        "Happy vibes only! Let’s keep it that way.",
        "You’ve got such a positive energy! Let’s make the most of it.",
        "So much happiness! Let’s turn it into something even better.",
        "Feeling awesome? Let’s explore something exciting!",
        "Hello, happy soul! Let’s make this moment extraordinary.",
        "You’re beaming with joy! What’s the secret?",
        "This happiness suits you perfectly. Let’s make it last!",
        "Feeling cheerful? Let’s double the fun together.",
        "Smiling already? Let’s keep the momentum going!",
        "You’re full of life today! Let’s channel it into something amazing.",
        "Let’s bottle up this happiness and sprinkle it everywhere!",
        "Your positive vibes are truly inspiring! Let’s keep them going.",
        "Radiating joy? Let’s make this moment even more special!",
        "Your happiness is infectious! Let’s spread it far and wide.",
        "Feeling bright and bubbly? Let’s keep the fun rolling!",
        "It’s a great day to be happy, and you’re leading the charge!",
        "Your happiness lights up the room! Let’s shine brighter.",
        "Feeling amazing? Let’s make this day unforgettable!",
        "Your joy is like sunshine on a cloudy day. Keep shining!",
        "Smiles all around! Let’s make this moment even better.",
        "The world looks better with your happiness in it!",
        "You’re on top of the world, and I’m here to cheer you on!",
        "Happiness overload! Let’s channel it into something creative.",
        "You’re unstoppable today! Let’s keep the positivity flowing.",
        "Joyful moments like this deserve a celebration!",
        "Your happiness is the highlight of my day!",
        "Feeling great? Let’s take it to the next level!",
        "Your good vibes are truly magical. Let’s keep them alive.",
        "Wow, your energy is amazing! Let’s make something special happen.",
        "It’s a joy to see you so happy! Let’s make it last.",
        "Let’s turn this happiness into a masterpiece!",
        "You’re radiating joy, and it’s inspiring me too!",
        "Happiness is in the air, and you’re the source!",
        "You’re like a ray of sunshine! Let’s spread that light everywhere.",
        "It’s such a great vibe today! Let’s keep it going.",
        "Your cheerful energy is lighting up everything around you!",
        "Feeling fantastic? Let’s dive into something amazing together.",
        "You’re shining so bright today! Let’s make the most of it.",
        "Your smile is a superpower! Let’s use it to spread happiness.",
        "You’re on a roll! Let’s keep this joyful ride going.",
        "So much happiness! Let’s make it even better together.",
        "You’re like a walking celebration! Let’s party!",
        "Your happiness is my happiness. Let’s enjoy this moment!",
        "It’s a joy to see you in such high spirits!",
        "Happiness suits you so well! Let’s make it unforgettable.",
        "Your positivity is contagious. Let’s keep spreading it!",
        "Feeling amazing? Let’s share that joy with the world.",
        "Your smile is everything today. Let’s brighten the day further!",
        "You’re absolutely glowing with joy! Let’s celebrate it.",
        "The world needs more of your happiness. Let’s make it happen!",
        "Your cheerful vibes are my favorite thing today!",
        "Let’s channel all this happiness into something wonderful.",
        "Feeling incredible? Let’s make this moment one to remember.",
        "You’re on fire today with all that positivity!",
        "Wow, your joy is so inspiring! Let’s spread it everywhere.",
        "Let’s bottle up this happiness and save it for a rainy day!",
        "You’re a ball of sunshine today! Let’s light up the world.",
        "Your good mood is lighting up the entire space!",
        "Happiness overload? Let’s double it with a fun idea!",
        "You’re rocking this positive vibe! Let’s make it last.",
        "Your happiness is a reminder that life is beautiful.",
        "Let’s turn this amazing mood into an unforgettable adventure.",
        "The world feels brighter with your happiness in it!",
        "You’re beaming with joy! What an amazing sight!",
        "Feeling on top of the world? Let’s keep climbing together.",
        "Let’s make this joyful moment even more special.",
        "You’re a ray of positivity! Let’s share it with everyone.",
        "Feeling great? Let’s channel it into something creative.",
        "Your happiness is the fuel we need for an awesome day.",
        "Let’s ride this wave of joy and make it even bigger!",
        "You’re unstoppable with all that positivity. Let’s celebrate!",
        "Happiness suits you so well. Let’s keep the momentum going!",
        "Your cheerful energy is like music to my ears!",
        "Feeling amazing? Let’s make this the highlight of the day.",
        "Your joy is so inspiring. Let’s spread it far and wide!",
        "Happiness overload? Let’s turn it into an adventure!",
        "You’re absolutely glowing with good vibes. Let’s share them!",
        "Feeling incredible? Let’s make this moment unforgettable.",
        "Your positivity is so refreshing. Let’s bottle it up!",
        "Let’s make this joyful vibe even more special.",
        "Your happiness lights up my world. Let’s keep shining!",
        "Feeling great? Let’s explore something exciting together.",
        "You’re a bundle of joy today! Let’s celebrate it.",
        "Your smile is everything! Let’s keep it alive.",
        "So much positivity! Let’s channel it into something amazing.",
        "Happiness overload? Let’s turn it into a masterpiece!",
        "You’re rocking that joyful vibe! Let’s share it with the world.",
        "Feeling fantastic? Let’s make this day unforgettable.",
        "Your cheerful energy is the best thing ever! Let’s keep it up.",
        "Your happiness is contagious! Let’s spread it everywhere.",
        "You’re a ray of sunshine today. Let’s brighten the day further.",
        "Feeling incredible? Let’s make this moment one to remember.",
    ],
    "neutral": [
        "Hey there! Let’s turn this ordinary moment into something extraordinary.",
        "Feeling neutral? Let’s spice things up with a quirky opener!",
        "Not much going on? Let me change that with something fun.",
        "How about we make this moment a little more exciting?",
        "Let’s take this neutral vibe and explore something cool together.",
        "Just another day? Let’s make it a little brighter.",
        "Feeling in between? Let’s discover something interesting!",
        "Not sure how you feel? That’s okay—let’s dive into a new idea.",
        "Let’s turn this calm moment into a spark of inspiration.",
        "Neutral vibes? Perfect time for a little creative exploration!",
        "How about we make this ordinary moment a bit extraordinary?",
        "Feeling steady? Let’s add a dash of fun to your day.",
        "Sometimes neutral is just the calm before the excitement!",
        "Let’s use this moment to try something new and fun.",
        "Feeling indifferent? Let’s see if we can stir up some inspiration.",
        "Neutral’s a great starting point for something unexpected!",
        "How about we turn this moment into a little adventure?",
        "Let’s turn this neutral pause into a burst of creativity.",
        "Sometimes doing nothing is the best time to try something fun.",
        "Feeling neutral is a perfect time to explore a new thought!",
        "Not much going on? Let me share something to brighten your day.",
        "Let’s take this steady vibe and make it a little more dynamic.",
        "Feeling neutral? That’s a blank canvas for creativity!",
        "Neutrality can be underrated—let’s make it exciting!",
        "How about we turn this simple moment into something special?",
        "Feeling neutral is a great time to spark a little joy.",
        "Let’s see if we can turn neutral into something fun and unexpected!",
        "Neutral moments are perfect for surprising ideas!",
        "Not much happening? Let’s change that with a fresh idea.",
        "Sometimes, neutral just means there’s room for something great.",
        "Let’s take this moment and make it more engaging together.",
        "Neutral is the perfect time to explore something fun and new!",
        "How about we add a little excitement to this moment?",
        "Feeling steady? Let’s add a twist to your day!",
        "Neutral vibes? Let’s turn them into something memorable.",
        "Sometimes, a neutral mood is just the start of a great idea!",
        "Let’s take this quiet moment and make it extraordinary.",
        "Neutral energy? Let’s channel it into something cool.",
        "Nothing much going on? Let’s create a little spark of joy.",
        "Neutral vibes are a great base for creativity—let’s explore!",
        "Feeling balanced? Let’s turn it into something exciting!",
        "Neutral is just a step away from inspired—let’s find it!",
        "Let’s turn this steady moment into something energizing.",
        "Neutral moments are perfect for a bit of fun. Ready?",
        "How about a little idea to brighten this neutral moment?",
        "Feeling calm? Let’s channel that into something creative.",
        "Let’s use this neutral moment to discover something surprising.",
        "Not feeling much? Let’s see if we can bring some excitement.",
        "Neutral moods are the perfect time for new beginnings.",
        "Let’s make this calm moment a little more dynamic!",
        "Feeling neutral? Let’s turn this into an opportunity to explore.",
        "Sometimes, a neutral vibe is the calm before the fun!",
        "Let’s use this balance to spark something creative.",
        "Neutrality is the perfect place to try something new.",
        "Feeling steady? Let’s use it to start an interesting journey.",
        "Neutral moments are like blank pages—ready to be filled!",
        "How about a small twist to brighten this moment?",
        "Neutral can be peaceful—let’s make it exciting too.",
        "Not much going on? Let’s turn this moment into an adventure.",
        "Neutral times are perfect for thoughtful exploration.",
        "Feeling indifferent? Let’s see if we can change that!",
        "Neutral vibes can lead to great ideas—let’s explore together.",
        "This neutral moment is the perfect time to create something cool.",
        "Neutral doesn’t mean boring—let’s change things up!",
        "Feeling balanced? That’s a great place to start something new.",
        "Let’s add some color to this neutral moment.",
        "Neutral energy can be transformed into something fantastic!",
        "How about turning this steady vibe into something memorable?",
        "Neutral moments can lead to surprising ideas—let’s find one!",
        "Sometimes neutral is just the right mood to spark inspiration.",
        "Let’s use this calm moment to discover something fun.",
        "Feeling neutral is the perfect time to try something new.",
        "Neutral can be a starting point for amazing discoveries.",
        "Let’s turn this ordinary moment into an extraordinary one!",
        "How about we take this neutral mood and make it joyful?",
        "Neutral vibes are perfect for starting fresh ideas.",
        "Not feeling much? Let’s see what we can create together.",
        "Feeling steady? Let’s take it as a sign to try something fun!",
        "Neutral moments are great for quiet reflection—or adventure!",
        "Let’s turn this balanced vibe into something unforgettable.",
        "Neutral energy can go anywhere—let’s guide it somewhere great.",
        "Sometimes, neutral moments are the best for bold ideas!",
        "Let’s make this steady moment a stepping stone to fun.",
        "Feeling neutral is just an open door to the unexpected!",
        "Neutral moods are ideal for starting new adventures.",
        "Let’s take this neutral moment and make it inspiring.",
        "Feeling calm? Let’s use it as a foundation for creativity.",
        "Neutral energy is just waiting to be shaped—let’s do it!",
        "How about we turn this ordinary day into something special?",
        "Neutral is a perfect canvas—let’s paint something amazing on it.",
        "Let’s turn this balanced vibe into something exciting!",
        "Neutral moments are perfect for surprising new ideas.",
        "Feeling neutral? Let’s see where this moment can take us!",
        "Neutral moods are like puzzles waiting to be solved.",
        "Let’s use this calm vibe to try something fresh and fun.",
        "Not feeling much? That’s the best time to explore!",
        "Neutral energy can become anything—let’s guide it together.",
        "How about we use this steady vibe to create something unique?",
        "Feeling indifferent? Let’s turn it into curiosity!",
        "Neutral moments are the calm before the excitement!",
    ]
}

def get_opener(emotion):
    """Get a random opener based on the detected emotion."""
    if emotion in openers:
        return random.choice(openers[emotion])
    else:
        return "I’m not sure what you’re feeling, but let’s make this moment awesome!"

def detect_face_and_emotion():
    print("Initializing models...")

    # Load YOLO face detection model
    face_model_path = hf_hub_download(repo_id="arnabdhar/YOLOv8-Face-Detection", filename="model.pt")
    face_model = YOLO(face_model_path)

    # Load emotion classification model
    emotion_processor = AutoImageProcessor.from_pretrained("RickyIG/emotion_face_image_classification_v3")
    emotion_model = AutoModelForImageClassification.from_pretrained("RickyIG/emotion_face_image_classification_v3")

    print("Models loaded successfully.")

    # Initialize webcam
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        raise IOError("Cannot open webcam")

    try:
        while True:
            print("Waiting for face detection...")

            ret, frame = cap.read()
            if not ret:
                print("Failed to grab frame.")
                continue

            # Detect faces using YOLO
            results = face_model(frame)
            if len(results[0].boxes) > 0:  # If faces detected
                # Process the first detected face
                box = results[0].boxes[0]
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                face_region = frame[y1:y2, x1:x2]

                # Convert face to PIL Image for emotion detection
                pil_image = Image.fromarray(cv2.cvtColor(face_region, cv2.COLOR_BGR2RGB))

                # Perform emotion detection
                inputs = emotion_processor(pil_image, return_tensors="pt")
                with torch.no_grad():
                    logits = emotion_model(**inputs).logits
                predicted_emotion = emotion_model.config.id2label[logits.argmax().item()]

                # Display detected emotion and send to chatbot
                print(f"\nDetected Emotion: {predicted_emotion}")
                opener = get_opener(predicted_emotion)
                print(f"Chatbot Response: {opener}")
                speak(opener)

                # Wait 3 seconds before restarting detection
                print("Waiting 3 seconds before restarting...")
                time.sleep(3)
                continue

            # Show live preview
            cv2.imshow("Face Detection (Press 'q' to quit)", frame)

            # Exit on 'q' key
            if cv2.waitKey(1) & 0xFF == ord('q'):
                print("Exiting program.")
                break

    finally:
        # Clean up
        cap.release()
        cv2.destroyAllWindows()

if __name__ == "__main__":
    try:
        detect_face_and_emotion()
    except Exception as e:
        print(f"An error occurred: {str(e)}")
